name: flutter_sentry
description: >
  Sentry.io error reporting plugin for Flutter, offering tight integration with
  Flutter and native code.
version: 0.8.1
homepage: https://github.com/dasfoo/flutter_sentry

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  device_info: ^1.0.0
  flutter:
    sdk: flutter
  # https://pub.dev/packages/http/changelog 0.13.0+ is a breaking API change
  # which our dependency, sentry, is incompatible with.
  http: ^0.12.2
  meta: ^1.2.3
  # package_info is migrating to 1.0.0 and asks us to use this constraint.
  package_info: ">=0.4.0 <2.0.0"
  sentry: ^4.0.0
  uuid: ">=2.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0
  test: ^1.9.4

flutter:
  plugin:
    platforms:
      android:
        package: org.dasfoo.flutter_sentry
        pluginClass: FlutterSentryPlugin
      ios:
        pluginClass: FlutterSentryPlugin
